-- H2-compatible baseline for tests
CREATE TABLE IF NOT EXISTS personas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    pronouns VARCHAR(255),
    description VARCHAR(1000),
    other_details VARCHAR(1000),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS stanzas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id BIGINT NOT NULL,
    world_identifier VARCHAR(100),
    status VARCHAR(20),
    current_beat INTEGER,
    current_exchange INTEGER,
    time_context VARCHAR(500),
    world_state VARCHAR(1000),
    world_rules VARCHAR(10000),
    locations CLOB,
    setting VARCHAR(500),
    premise VARCHAR(1000),
    tone VARCHAR(200),
    quick_synopsis VARCHAR(2000),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_stanzas_persona FOREIGN KEY (persona_id) REFERENCES personas(id)
);

CREATE TABLE IF NOT EXISTS beats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stanza_id BIGINT NOT NULL,
    beat_number INTEGER NOT NULL,
    start_exchange INTEGER NOT NULL,
    end_exchange INTEGER,
    transition_context CLOB,
    summary CLOB,
    created_at TIMESTAMP(6),
    completed_at TIMESTAMP(6),
    CONSTRAINT fk_beats_stanza FOREIGN KEY (stanza_id) REFERENCES stanzas(id)
);

CREATE TABLE IF NOT EXISTS stanza_characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stanza_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_user BOOLEAN,
    canon_role VARCHAR(300),
    presence_status VARCHAR(20),
    public_role VARCHAR(500),
    private_backstory VARCHAR(2000),
    visible_traits VARCHAR(10000),
    emotional_state VARCHAR(300),
    motivations VARCHAR(10000),
    relationship_to_user VARCHAR(300),
    goals VARCHAR(10000),
    blueprint_tier1_essentials CLOB,
    blueprint_tier2_motivators CLOB,
    blueprint_tier3_anchors VARCHAR(10000),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_characters_stanza FOREIGN KEY (stanza_id) REFERENCES stanzas(id)
);

CREATE TABLE IF NOT EXISTS stanza_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stanza_id BIGINT NOT NULL,
    beat_id BIGINT,
    description VARCHAR(280) NOT NULL,
    beat_number INTEGER,
    exchange_number INTEGER,
    involved_characters VARCHAR(300),
    is_major BOOLEAN,
    created_at TIMESTAMP(6),
    CONSTRAINT fk_events_stanza FOREIGN KEY (stanza_id) REFERENCES stanzas(id),
    CONSTRAINT fk_events_beat FOREIGN KEY (beat_id) REFERENCES beats(id)
);