-- H2-compatible chats and messages
CREATE TABLE IF NOT EXISTS chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id BIGINT NOT NULL,
    stanza_id BIGINT,
    title VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_chats_persona FOREIGN KEY (persona_id) REFERENCES personas(id),
    CONSTRAINT fk_chats_stanza FOREIGN KEY (stanza_id) REFERENCES stanzas(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    mode VARCHAR(10) NOT NULL,
    role VARCHAR(10) NOT NULL,
    exchange_number INTEGER,
    content CLOB NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_messages_chat FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE
);

CREATE INDEX idx_chat_messages_chat_created ON chat_messages (chat_id, created_at);