-- H2-compatible synopsis history
CREATE TABLE IF NOT EXISTS synopsis_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stanza_id BIGINT NOT NULL,
    exchange_number INTEGER NOT NULL,
    synopsis_text CLOB NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_synopsis_stanza FOREIGN KEY (stanza_id) REFERENCES stanzas(id) ON DELETE CASCADE
);

CREATE INDEX idx_synopsis_stanza_exchange ON synopsis_history (stanza_id, exchange_number DESC);